---
printWidth: 100
tabWidth: 2
useTabs: true
trailingComma: all
semi: true
singleQuote: true
overrides:
  - files: '**/*.md'
    options:
      tabWidth: 2
plugins:
  - prettier-plugin-organize-imports
